-- ============================================================================
-- Migration Name: 06_pr_approval_and_batching
-- Description: Implements PR-to-PO status tiers, staged requisition staging,
--              automated approval processing, and vendor batch consolidation.
--              Includes strict SAP data dictionary references.
-- ============================================================================

-- 0. CLEANUP PREVIOUS OBJECTS TO ENSURE DDL COMPILATION
DROP VIEW IF EXISTS public.v_sap_consolidated_batch_payload CASCADE;
DROP FUNCTION IF EXISTS public.approve_staged_requisitions(text[], text);
DROP TABLE IF EXISTS public.erp_staged_requisitions CASCADE;
DROP TABLE IF EXISTS public.erp_requisition_batches CASCADE;
DROP TYPE IF EXISTS public.pr_status_tier CASCADE;

-- 1. STATE STATUS ENUM
-- Represents the SAP Purchase Requisition (PR) to Purchase Order (PO) lifecycle stages:
-- - STAGED: Requisition generated by store but pending manager sign-off.
-- - APPROVED: Verification completed, queued for batch dispatch.
-- - TRANSMITTED: Handshake completed, successfully routed to SAP S/4HANA.
CREATE TYPE public.pr_status_tier AS ENUM ('STAGED', 'APPROVED', 'TRANSMITTED');

-- 2. CREATE REQUISITION BATCHES REFERENCE TABLE
CREATE TABLE public.erp_requisition_batches (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_by UUID
);

COMMENT ON TABLE public.erp_requisition_batches IS 'Aggregated purchase order batches grouped and sent to SAP.';

-- 3. CREATE STAGED REQUISITIONS TABLE
-- Models SAP EBAN (Purchase Requisition) and EBKN (Account Assignment) table attributes.
CREATE TABLE public.erp_staged_requisitions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- SAP Material Number (MATNR). Target SKU for purchase.
    sku VARCHAR(40) NOT NULL,
    
    -- SAP Order Quantity (MENGE). Number of units to order.
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    
    -- SAP Plant Code (WERKS). Receiving warehouse plant.
    plant VARCHAR(4) NOT NULL,
    
    -- SAP Storage Location (LGORT). Receiving store storage location.
    storage_location VARCHAR(4) NOT NULL,
    
    -- PR Status Tier. Tracks verification workflow.
    status public.pr_status_tier DEFAULT 'STAGED'::public.pr_status_tier NOT NULL,
    
    -- Requisition Approver UID (USNAM equivalent). Reference to authorizing store manager.
    approved_by UUID,
    
    -- Requisition Approval Timestamp (ERDAT/UZEIT equivalent).
    approved_at TIMESTAMP WITH TIME ZONE,
    
    -- Consolidated Batch Linkage. FK referencing erp_requisition_batches.
    batch_id UUID REFERENCES public.erp_requisition_batches(id) ON DELETE SET NULL,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

COMMENT ON TABLE public.erp_staged_requisitions IS 'Staged purchase requisitions matching SAP S/4HANA EBAN/EBKN structures.';

-- 4. ENABLE ROW LEVEL SECURITY & DEFINE POLICIES
ALTER TABLE public.erp_requisition_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.erp_staged_requisitions ENABLE ROW LEVEL SECURITY;

CREATE POLICY access_all_requisition_batches ON public.erp_requisition_batches
    FOR ALL USING (true);

CREATE POLICY access_all_staged_requisitions ON public.erp_staged_requisitions
    FOR ALL USING (true);

-- 5. CREATE INDEXES FOR RELATION OPTIMIZATIONS
CREATE INDEX idx_staged_req_sku ON public.erp_staged_requisitions (sku);
CREATE INDEX idx_staged_req_status ON public.erp_staged_requisitions (status);
CREATE INDEX idx_staged_req_batch_id ON public.erp_staged_requisitions (batch_id);

-- 6. THE APPROVAL STORED PROCEDURE
-- Validates manager signature, transitions targets from STAGED to APPROVED,
-- and aggregates financial yield gains based on sales margin definitions.
CREATE OR REPLACE FUNCTION public.approve_staged_requisitions(
    target_skus TEXT[],
    manager_uid TEXT
)
RETURNS TABLE (
    total_approved_items INTEGER,
    total_approved_qty BIGINT,
    total_financial_yield NUMERIC(10, 2)
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_manager_uuid UUID;
BEGIN
    -- Force typecast check
    v_manager_uuid := manager_uid::UUID;

    -- Update matched staged records to APPROVED status
    UPDATE public.erp_staged_requisitions
    SET 
        status = 'APPROVED'::public.pr_status_tier,
        approved_by = v_manager_uuid,
        approved_at = timezone('utc'::text, now()),
        updated_at = timezone('utc'::text, now())
    WHERE sku = ANY(target_skus)
      AND status = 'STAGED'::public.pr_status_tier;

    -- Return consolidated summary of the approved items
    RETURN QUERY
    SELECT 
        COUNT(r.id)::INTEGER AS total_approved_items,
        COALESCE(SUM(r.quantity), 0)::BIGINT AS total_approved_qty,
        COALESCE(SUM(r.quantity * l.sales_margin), 0.00)::NUMERIC(10, 2) AS total_financial_yield
    FROM public.erp_staged_requisitions r
    LEFT JOIN public.live_inventory_ledger l 
      ON r.sku = l.sku 
     AND r.plant = l.sap_plant_code 
     AND r.storage_location = l.sap_storage_loc
    WHERE r.sku = ANY(target_skus)
      AND r.status = 'APPROVED'::public.pr_status_tier
      AND r.approved_by = v_manager_uuid
      AND r.approved_at >= timezone('utc'::text, now()) - INTERVAL '1 minute';
END;
$$;

COMMENT ON FUNCTION public.approve_staged_requisitions(text[], text) IS 'Approves staged requisitions and aggregates financial yield metrics.';

-- 7. THE SAP BATCH OPTIMIZER VIEW
-- Prepares multi-line OData $batch structures grouped by Vendor Account (LIFNR) for edge worker transmission.
CREATE OR REPLACE VIEW public.v_sap_consolidated_batch_payload AS
SELECT 
    pir.vendor_id,
    pir.vendor_name,
    COUNT(r.id)::INTEGER AS total_requisitions,
    SUM(r.quantity)::BIGINT AS total_quantity,
    json_agg(
        json_build_object(
            'sku', r.sku,
            'plant', r.plant,
            'storage_location', r.storage_location,
            'quantity', r.quantity,
            'netpr_price', pir.netpr_price,
            'matkl_group', pir.matkl_group
        )
    ) AS items
FROM public.erp_staged_requisitions r
JOIN public.erp_purchase_info_records pir ON r.sku = pir.sku
WHERE r.status = 'APPROVED'::public.pr_status_tier
GROUP BY pir.vendor_id, pir.vendor_name;

COMMENT ON VIEW public.v_sap_consolidated_batch_payload IS 'Vendor consolidated PO payloads formatted for SAP $batch OData structures.';
